# Unrecoverable Errors with `panic!`

Macro that causes a program to print a failure message, unwind and clean up the
stack and then quit.

- Unwind = walk back up the stack and clean up the data from each function
  - Instead of aborting immediately and relying on the OS to clean up memory

**Backtrace** = list of all the functions that have been called to reach the point
in the program where a `panic!` occurs

- Set `RUST_BACKTRACE=1` environment variable to enable backtrace printing

# Recoverable Errors with `Result`

`Result` is an `Enum` with two variants, `Ok` and `Err`:

- Included in the prelude

```rust
enum Result<T, E>a {
    Ok(T),
    Err(E),
}
```

Use `match` to specify behaviour for each case:

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("Problem opening the file: {:?}", error)
        },
    };
}
```

Use `unwrap` or `expect` to panic in case of `Err`:

```rust
use std::fs::File;

fn main() {
    // Panic if Err opening file
    let f1 = File::open("hello.txt").unwrap();
    // Panic if Err opening file, including specified message in error message
    let f2 = File::open("hello2.txt").expect("Failed to open hello2.txt");
}
```

Propagating errors using `?` operator:

- If a `Result` value is an `Ok`, return the `Ok` value and continue
- If a `Result` value is an `Err`, return the `Err` from the whole function
  - `?` uses the `from` function provided by the `From` trait is used to convert
    the `Err` to the error type in the return type of the current function
- Must be used within a function that returns `Result`, `Option` or another type that implements `std::ops::Try`

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open?.read_to_string(&mut s)?;
    Ok(s)
}

```

Note, the above function could be implemented more succinctly using `fs::read_to_string` which provides the same error propagation

- Built in as reading a file into a string is a common operation

```rust
use std::io;
use std::fs;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

## Custom Types for Validation

Make it safe to use and receive values without the need to perform validation at each site.

Replace:

```rust
// --snip--
loop {
    let mut guess = String::new();

    io::stdin()
        .read_line(&mut guess)
        .expect("Failed to read line");


    let guess: i32 = match guess.trim().parse() {
        Ok(num) => num,
        Err(_) => continue,
    };

    // Repeat this check everywhere a guess is used
    if guess < 1 || guess > 100 {
        println!("The secret number will be between 1 and 100.");
        continue;
    }

    match guess.cmp(&secret_number){
    // --snip--
}
```

With:

```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    // Restrict values of Guess to 1..100
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess {
            value
        }
    }

    pub fn value(&self) -> i32 {
        self.value
    }
}
// --snip--
loop {
    let mut guess = String::new();

    io::stdin()
        .read_line(&mut guess)
        .expect("Failed to read line");


    let guess: Guess = match guess.trim().parse() {
        Ok(value) => Guess{value},
        Err(_) => continue,
    };

    match guess.value().cmp(&secret_number){
    // --snip--
}
```
